events {
    # Impostazioni base per le connessioni concorrenti
    worker_connections 1024;
}

http {
    # Definiamo il nostro "Cluster" di server Node.js
    upstream websocket_cluster {
        # ==========================================
        # LA MAGIA DELLE STICKY SESSIONS
        # ==========================================
        # 'hash' usa una variabile per decidere a quale server inviare la richiesta.
        # '$arg_documentId' estrae il parametro '?documentId=' dall'URL.
        # 'consistent' evita di rimescolare tutti gli utenti se aggiungiamo un Backend 3.
        
        #hash $arg_documentId consistent;
        hash $arg_documentId;

        # I nostri due server (i nomi corrispondono ai container Docker)
        server backend1:3000;
        server backend2:3000;
    }

    server {
        listen 80; # Il Load Balancer risponde sulla porta 80 standard

        location / {
            # Inoltra il traffico al cluster
            proxy_pass http://websocket_cluster;

            # Configurazioni OBBLIGATORIE per far funzionare i WebSocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            
            # Passiamo l'IP reale del client ai server Node
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}